### PR TITLE
Deputations

### PR DESCRIPTION
**Pull request by entantoencuanto**
## Changes in controllers and views to display data for deputations

This PR:
* Changes the paths to have deputations show paths
* Updates controllers, views and models to manage a separated collection of deputation places in addition of the municipalities
* Adds the show view of deputations https://presupuestos.gobify.net/diputaciones/dip-bizkaia/2023.
* Changes the task to load extra data to generate population data by province and autonomous region and uses this data in population of deputations
* Adapts views to not have references to municipalities and contratos on deputations pages
* Fixes the rankings filter to use separated paths for municipalities and deputations
* Fixes some bugs in the rankings page:
  * Fixes the population filter
  * Corrects an internal parameter allowing to filter by population and autonomous region
  * Fixes the pagination refresh
* Changes the calculations of province, autonomic and national budget lines expenses by inhabitant averages shown in lines charts of municipalities pages to use only data from municipalities
* Changes the lines chart displayed data depending on the context of municipality or deputations (see https://github.com/PopulateTools/issues/issues/1882#issuecomment-1967497973)
* Changes the -100% value of executed vs. planned on maps when the global executed value is zero to show a "Not available" message (see https://github.com/PopulateTools/issues/issues/1913#issuecomment-1967501273)
* Changes the autocomplete js to use a configurable in settings.yml list of municipalities allowing the searches to restrict the list used

### CODE REVIEW

**Comment by furilo** [comment]
What changes have been covered? What should I review already?

**Comment by entantoencuanto** [comment]
It's partially in progress. The most detailed items to check are currrently in https://github.com/PopulateTools/issues/issues/1891 I'm going to finish the tasks there and then move to the comparison and rankings sections

**Comment by furilo** [comment]
What is pending here for the merge?

**Comment by furilo** [comment]
When you enter here https://presupuestos.gobify.net/ranking/2023/G/functional/amount_per_inhabitant/336 you are shown all places, but as soon as you use any filter, it seems only places from Euskadi are shown. 

Which is the status of data in staging?

**Comment by entantoencuanto** [comment]
I have to review the filter paths, probably the main problem is the configuration of paths I'm fixing it

**Pull request merged**
