### PR TITLE
Fix ranking filters

### LINKED ISSUE #166: Place population filter is not working in ranking
In https://presupuestos.gobierto.es/ranking/2017/I/economic/amount/6?&f[population][from]=10000&f[population][to]=50000&f[total][from]=900000&f[total][to]=5000000000&f[per_inhabitant][from]=0&f[per_inhabitant][to]=20000 - if you change de population filter, it is not applied.

### PR DESCRIPTION
**Pull request by amiedes**
Closes #166 and [#612](https://github.com/PopulateTools/issues/issues/612)

### CODE REVIEW

**Comment by amiedes** [comment]
This can be reviewed in http://presupuestos.gobify.net/ranking/2018/G/functional/amount

**Comment by amiedes** [comment]
Pending to resolve https://github.com/PopulateTools/gobierto-comparador-presupuestos/issues/166

**Comment by amiedes** [comment]
@ferblape the population filter was failing for a specific budget line, now it's fixed: http://presupuestos.gobify.net/ranking/2018/I/economic/amount/554-00?f%5Bper_inhabitant%5D%5Bfrom%5D=0&f%5Bper_inhabitant%5D%5Bto%5D=20000&f%5Bpopulation%5D%5Bfrom%5D=500000&f%5Bpopulation%5D%5Bto%5D=5000000&f%5Btotal%5D%5Bfrom%5D=0&f%5Btotal%5D%5Bto%5D=5000000000#

**Comment by ferblape** [comment]
Yep, thanks. I can see everything is working now. I'll release it on Monday.

**Pull request merged**
